# the units of the parameters is m, rad, m/s, m/s^2, g, pixel
#robot ip and port
name: Franka1
ip: 192.168.1.102
port: 30003
velocity: 25 #scale [0~100]
acceleration: 1.2
home_joint: [0.6, 0.0, 0.4, 3.14, 0.0, 0.0]
home_pose: None
