initial_position:
  - 0.45
  - -0.25
  - 0.4
  - 0.5
  - 0.0
  - 0.0

x_stride: 0.1
y_stride: 0.15
z_stride: 0.15

rotation_upper_limit: 0.5
rotation_lower_limit: -0.5

marker_size: 0.055 # in meter
marker_repeat_sample: 10

sample_cube_size: 3 # Totally sampled points = size ^ 3

board_offset_x: 0
board_offset_y: 0
board_offset_z: 0

save_dir: /cali_data/
